version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t your-image-name .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - $(aws ecr get-login --no-include-email --region your-region)
      - docker tag your-image-name:latest your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:latest
      - docker push your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:latest
      - echo Creating imagedefinitions.json file...
      - printf '[{"name":"your-container-name","imageUri":"%s"}]' your-account-id.dkr.ecr.your-region.amazonaws.com/your-repo-name:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
